global:
  scrape_interval: 15s  # Intervalo de recolección de métricas

scrape_configs:
  - job_name: "eureka-server"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["eureka-server:8761"]
        labels:
          service: "eureka-server"